### ISSUE TITLE
Missing required argument $host of Symfony\Component\VarDumper\Server\DumpServer. Type a message here

### ISSUE THREAD

**Issue by 619frank** [DuckThom/magento2-dump-server#1]
this error has been thrown when i run

bin/magento cache:flush

Missing required argument $host of Symfony\Component\VarDumper\Server\DumpServer. Type a message here

**Comment by DuckThom** [comment]
I'm aware of this issue, but I haven't had time to look into the cause yet.
It looks like it happens after a `setup:di:compile`. What's working for me is to set Magento in developer mode so that that command is not needed.

**Comment by DuckThom** [comment]
@619frank I've released a new version `1.0.2` which should hopefully contain a fix for this issue
